Fix: grant step3

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,22 +33,6 @@ jobs:
         sudo chown -R $USER:$USER src/logs
         chmod -R 777 src/logs
 
-    # - name: Create mysql-variables.env file
-    #   run: |
-    #     echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > mysql-variables.env
-    #     echo "MYSQL_APP_USER=${{ secrets.MYSQL_APP_USER }}" >> mysql-variables.env
-    #     echo "MYSQL_APP_USER_PASSWORD=${{ secrets.MYSQL_APP_USER_PASSWORD }}" >> mysql-variables.env
-    
-    # - name: Create .env file
-    #   run: |
-    #     echo "LOGGING_DIR=src/logs" > .env
-    #     echo "CI=true" >> .env
-    #     echo "MYSQL_HOST=db" >> .env
-    #     echo "MYSQL_PORT=3306" >> .env
-    #     echo "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}" >> .env
-    #     echo "MYSQL_TEST_DB_NAME=${{ secrets.MYSQL_TEST_DB_NAME }}" >> .env
-    #     echo "MYSQL_APP_USER=${{ secrets.MYSQL_APP_USER }}" >> .env
-    #     echo "MYSQL_APP_USER_PASSWORD=${{ secrets.MYSQL_APP_USER_PASSWORD }}" >> .env
     - name: Create .env file
       run: |
         echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
@@ -84,30 +68,27 @@ jobs:
         pip install --upgrade pip
         pip install -r requirements.txt
     
-    - name: Reload .env file
-      run: |
-        if [ -f .env ]; then
-          echo "Reloading .env file..."
-          while IFS= read -r line; do
-            if [[ "$line" != \#* && "$line" != "" ]]; then
-              export "$line"
-              echo "$line" >> $GITHUB_ENV
-            fi
-          done < .env
-        else
-          echo ".env file not found."
-          exit 1
-        fi
+    # - name: Reload .env file
+    #   run: |
+    #     if [ -f .env ]; then
+    #       echo "Reloading .env file..."
+    #       while IFS= read -r line; do
+    #         if [[ "$line" != \#* && "$line" != "" ]]; then
+    #           export "$line"
+    #           echo "$line" >> $GITHUB_ENV
+    #         fi
+    #       done < .env
+    #     else
+    #       echo ".env file not found."
+    #       exit 1
+    #     fi
     
     - name: Grant MySQL privileges for app_user
       run: |
         docker-compose exec -T db sh -c "
           MYSQL_PWD='${{ secrets.MYSQL_ROOT_PASSWORD }}' mysql -u root -e '
             DROP USER IF EXISTS '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\''; 
-            CREATE USER '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\'' IDENTIFIED BY '\''${{ secrets.MYSQL_APP_USER_PASSWORD }}'\'';'
-          "
-        docker-compose exec -T db sh -c "
-          MYSQL_PWD='${{ secrets.MYSQL_ROOT_PASSWORD }}' mysql -u root -e '
+            CREATE USER '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\'' IDENTIFIED BY '\''${{ secrets.MYSQL_APP_USER_PASSWORD }}'\''; 
             GRANT ALL PRIVILEGES ON *.* TO '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\''; 
             FLUSH PRIVILEGES;'
         "
